import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="logo">
            <Image src="https://dstal.com.au/wp-content/uploads/2021/09/logoipsum.png" alt="Logo" width={100} height={50} />
          </div>
          <nav>
            <ul>
              <li><Link href="/">Home</Link></li>
              <li><Link href="/about-us">About Us</Link></li>
              <li className="dropdown">
                Trails
                <ul className="dropdown-content">
                  <li><Link href="/trails/ten-km">10 km</Link></li>
                  <li><Link href="/trails/twentyfour-km">24 km</Link></li>
                  <li><Link href="/trails/guide">Guide</Link></li>
                  <li><Link href="/trails/registered-runners">Registered Runners</Link></li>
                </ul>
              </li>
              <li><Link href="/contact">Contact</Link></li>
              <li><Link href="/accommodation">Accommodation</Link></li>
              <li><Link href="/sponsors">Sponsors</Link></li>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <style jsx>{`
          .logo {
            float: left;
          }
          nav ul {
            list-style: none;
            padding: 0;
          }
          nav ul li {
            display: inline;
            margin-right: 20px;
          }
          .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
          }
          .dropdown:hover .dropdown-content {
            display: block;
          }
          .dropdown-content li {
            display: block;
            padding: 12px 16px;
          }
        `}</style>
      </body>
    </html>
  );
}
